name: Build rubbish-day Docker Images

on:
  push:
    paths-ignore:
      - README.md
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - README.md
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the rubbish-day Docker image
        run: |
          docker build . --tag ghcr.io/reubznz/rubbish-day:latest
          docker push ghcr.io/reubznz/rubbish-day:latest
